# Site settings
title: Aligned Emergence
description: 'Intuition over jargon. Questions over hype. A curiosity-driven exploration of AI alignment, interpretability, and the path to beneficial emergence.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "" # empty for root domain deployment
url: "https://aligned-emergence.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/ae-logo-full.svg"
logo-icon: "/assets/img/branding/ae-symbol.svg"
logo-icon-SEO: "/assets/img/branding/ae-symbol.png" # must be a non SVG file - you'll need to create this PNG version
# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"
logo-dark: "/assets/img/branding/ae-logo-full-dark.svg" # you'll need to create a dark version
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Your Name # replace with your actual name
author-pic: your-photo.jpg # replace with your photo filename
about-author: AI researcher and writer exploring the intersection of technology and human values. Passionate about making AI alignment accessible through curiosity-driven exploration and clear, jargon-free communication.

# Contact links
email: your-email@gmail.com # Add your Email address
phone: # Add your Phone number if desired
website: https://aligned-emergence.com # Your main website
linkedin: your-linkedin-handle # Add your Linkedin handle
github: your-github-handle # Add your Github handle
twitter: '@your-twitter-handle' # Add your Twitter handle
bandcamp: # Add your Bandcamp username if you have one
stackoverflow: # Add your stackoverflow account if you have one

# Newsletter
mailchimp: "" # Add your Mailchimp signup URL when you set up newsletter

# Analytics & Tracking
analytics: # Add your Google Analytics ID when ready (e.g., G-XXXXXXXXXX)
fbadmin: # Add your Facebook admin ID if needed

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Extensions
extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: your-github-username/aligned-emergence # The GitHub repo URL for utterances comments
  issue_term: pathname # The GitHub issue label
  label: comments # The GitHub comments label
  theme: github-light # The GitHub comment's theme. e.g. github-dark, github-light
  # Disqus (alternative)
  discus_identifier: # Add your discus identifier if using Disqus instead

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: America/New_York # Update to your timezone - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
